spring:
  application:
    name: GooInProAdminAPI
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13307/gooinprodb
    username: gooinprodbuser
    password: gooinprodbuser
  data:
    mongodb:
      uri: mongodb://localhost:27017/gooinprochatdb

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true